FORMAT: 1A
HOST: https://drill.fprochazka.com/

# PB138: Drill

## Drills Collection [/drill]

### List all drills [GET]

+ Response 200 (application/json)

        {
            "drills": [
                {
                    "id": "5df783c6-0b09-4f1f-9db3-b22c5c9d003a",
                    "code": "PB138",
                    "name": "English II"
                },
                {
                    "id": "49643939-182d-499e-8988-8be6606d41e1",
                    "code": "MB102",
                    "name": "Diferenciální a integrální počet"
                },
                {
                    "id": "e5ccce88-3bd1-4955-b128-b88dd8d4eb60",
                    "code": "MB103",
                    "name": "Spojité modely a statistika"
                },
                {
                    "id": "c84fa430-0555-4198-a501-c3fee7ae4877",
                    "code": "MB104",
                    "name": "Diskrétní matematika"
                }
            ]
        }

### Create new drill [POST]

+ Request (application/json)

        {
            "code": "PB138",
            "name": "English II"
        }

+ Response 201 (application/json)

    + Headers

            Location: /drill/e5ccce88-3bd1-4955-b128-b88dd8d4eb60

    + Body

            {
                "id": "e5ccce88-3bd1-4955-b128-b88dd8d4eb60",
                "code": "PB138",
                "name": "English II"
            }

## Questions Collection [/drill/{drill_id}/question]

+ Parameters
    + drill_id (number) - ID of the relevant drill

### List questions in drill [GET]

+ Response 200 (application/json)

    + Body
        
            {
                "questions": [
                    {
                        "id": "0d58d80d-5616-4242-acd5-e75ede8cc0de",
                        "title": "Ako sa mas??"
                        "answers": [
                            { "text": "Super!", "correct": true },
                            { "text": "Fakt naprd...", "correct": false }
                        ]
                    }
                ]
            }

### Add new question to drill [POST]

+ Request (application/json)
            
    + Body

            {
                "title": "Ako sa mas??"
                "answers": [
                    { "text": "Super!", "correct": true },
                    { "text": "Fakt naprd...", "correct": false }
                ]
            }
        
+ Response 201 (application/json)

    + Headers

            Location: /drill/e5ccce88-3bd1-4955-b128-b88dd8d4eb60/question/0d58d80d-5616-4242-acd5-e75ede8cc0de

    + Body
        
            {
                "id": "0d58d80d-5616-4242-acd5-e75ede8cc0de",
                "title": "Ako sa mas??"
                "answers": [
                    { "text": "Super!", "correct": true },
                    { "text": "Fakt naprd...", "correct": false }
                ]
            }

## Question [/drill/{drill_id}/question/{question_id}]

+ Parameters
    + drill_id (number) - ID of the relevant drill
    + question_id (number) - ID of the question

### Read question [GET]

+ Response 200 (application/json)

    + Body
        
            {
                "id": "0d58d80d-5616-4242-acd5-e75ede8cc0de",
                "text": "Ako sa mas??"
                "answers": [
                    { "text": "Super!", "correct": true },
                    { "text": "Fakt naprd...", "correct": false }
                ]
            }

### Update question [PUT]

+ Request (application/json)

        {
            "title": "Ako sa mas??"
            "answers": [
                { "text": "Super!", "correct": false },
                { "text": "Fakt naprd...", "correct": true },
                { "text": "Idem na pivo.", "correct": true }
            ]
        }

+ Response 200 (application/json)

    + Body
        
            {
                "id": "0d58d80d-5616-4242-acd5-e75ede8cc0de",
                "title": "Ako sa mas??"
                "answers": [
                    { "text": "Super!", "correct": false },
                    { "text": "Fakt naprd...", "correct": true },
                    { "text": "Idem na pivo.", "correct": true }
                ]
            }
            
## Exam Collection [/user/{user_id}/exam]

+ Parameters

    + user_id (number) - ID of relevant user
    
### Create new exam [POST]

+ Request (application/json)

            {
                "drillId": "0d58d80d-5616-4242-acd5-e75ede8cc0de"
            }

+ Response 201 (application/json)

    + Headers

            Location: /user/{user_id}/exam/1

    + Body
    
            {
                "id": 1,
                "drillId": "0d58d80d-5616-4242-acd5-e75ede8cc0de",
                "answers": [ 
                    {
                        "question_id": "0d58d80d-5616-4242-acd5-e75ede8cc0de",
                        "correct": 0,
                        "wrong": 0
                    }
                ]
            }
            
### List all exams [GET]

+ Response 200 (application/json)

    + Body
    
            {
                "exams": [
                    {
                        "id": "6a7f2b1c-37fa-4674-9a9f-d005a131db75",
                        "drillId": "0d58d80d-5616-4242-acd5-e75ede8cc0de",
                        "answers": [ 
                            {
                                "questionId": "0d58d80d-5616-4242-acd5-e75ede8cc0de",
                                "correct": 0,
                                "wrong": 0
                            }
                        ]
                    }
                ]
            }


            
## Exam [/user/{userId}/exam/{examId}]

+ Parameters

    + userId (number) - ID of relevant user
    + examId (number) - ID of relevant exam

### Get exam details [GET]

+ Response 200 (application/json)

    + Body
    
            {
                "id": "6a7f2b1c-37fa-4674-9a9f-d005a131db75",
                "drillId": "0d58d80d-5616-4242-acd5-e75ede8cc0de",
                "answers": [ 
                    {
                        "questionId": "0d58d80d-5616-4242-acd5-e75ede8cc0de",
                        "correct": 0,
                        "wrong": 0
                    }
                ]
            }
            
### Update exam with answers [POST]

+ Request (application/json)

        {
            "answers": [
                {
                    "questionId": "6a7f2b1c-37fa-4674-9a9f-d005a131db75",
                    "correct": true
                }, 
                {
                    "questionId": "05017834-6be7-4046-a351-7d22d577efb3",
                    "correct": false
                }
            ]
        }
        
+ Response 200 (application/json)

## Answering question [/user/{userId}/exam/{examId}/question/{questionId}]

+ Parameters

    + userId (number) - ID of relevant user
    + examId (number) - ID of relevant exam
    + questionId (number) - ID of relevant question

### Get question in exam [GET]

+ Response 200 (application/json)

    + Body
    
            {
                "id": "05017834-6be7-4046-a351-7d22d577efb3",
                "text": "Ako sa mas??"
                "answers": [
                    { "text": "Super!", "correct": false },
                    { "text": "Fakt naprd...", "correct": true },
                    { "text": "Idem na pivo.", "correct": true }
                ]
            }