FORMAT: 1A
HOST: https://drill.fprochazka.com/

# PB138: Drill

## Drills Collection [/drill]

### List All Drills [GET]

+ Response 200 (application/json)

        [
            {
                "id": "123",
                "name": "PB138"
            }
        ]

### Create a New Question [POST]


+ Request (application/json)

        {
            "name": "PB138"
        }

+ Response 201 (application/json)

    + Headers

            Location: /drill/123

    + Body

            {
                "id": "123",
                "name": "PB138"
            }