FORMAT: 1A
HOST: https://drill.fprochazka.com/

# PB138: Drill

## Drills Collection [/drill]

### List all drills [GET]

+ Response 200 (application/json)

        {
            "drills": [
                {
                    "id": "123",
                    "name": "PB138"
                }
            ]
        }

### Create new drill [POST]

+ Request (application/json)

        {
            "name": "PB138"
        }

+ Response 201 (application/json)

    + Headers

            Location: /drill/123

    + Body

            {
                "id": "123",
                "name": "PB138"
            }

## Questions Collection [/drill/{drill_id}/question]

+ Parameters
    + drill_id (number) - ID of the relevant drill

### List questions in drill [GET]

+ Response 200 (application/json)

    + Body
        
            {
                "questions": [
                    {
                        "id": 44,
                        "text": "Ako sa mas??"
                        "answers": [
                            { "text": "Super!", "correct": true },
                            { "text": "Fakt naprd...", "correct": false }
                        ]
                    }
                ]
            }

### Add new question to drill [POST]

+ Request (application/json)
            
    + Body

            {
                "text": "Ako sa mas??"
                "answers": [
                    { "text": "Super!", "correct": true },
                    { "text": "Fakt naprd...", "correct": false }
                ]
            }
        
+ Response 201 (application/json)

    + Headers

            Location: /drill/123/question/44

    + Body
        
            {
                "id": 44,
                "text": "Ako sa mas??"
                "answers": [
                    { "text": "Super!", "correct": true },
                    { "text": "Fakt naprd...", "correct": false }
                ]
            }

## Question [/drill/{drill_id}/question/{question_id}]

+ Parameters
    + drill_id (number) - ID of the relevant drill
    + question_id (number) - ID of the question

### Read question [GET]

+ Response 200 (application/json)

    + Body
        
            {
                "id": 44,
                "text": "Ako sa mas??"
                "answers": [
                    { "text": "Super!", "correct": true },
                    { "text": "Fakt naprd...", "correct": false }
                ]
            }

### Update question [PUT]

+ Request (application/json)

        {
            "text": "Ako sa mas??"
            "answers": [
                { "text": "Super!", "correct": false },
                { "text": "Fakt naprd...", "correct": true },
                { "text": "Idem na pivo.", "correct": true }
            ]
        }

+ Response 200 (application/json)

    + Body
        
            {
                "id": 44,
                "text": "Ako sa mas??"
                "answers": [
                    { "text": "Super!", "correct": false },
                    { "text": "Fakt naprd...", "correct": true },
                    { "text": "Idem na pivo.", "correct": true }
                ]
            }
            
## Exam Collection [/user/{user_id}/exam]

+ Parameters

    + user_id (number) - ID of relevant user
    
### Create new exam [POST]

+ Request (application/json)

            {
                "drill_id": "123"
            }

+ Response 201 (application/json)

    + Headers

            Location: /user/{user_id}/exam/1

    + Body
    
            {
                "id": 1,
                "drill_id": 123,
                "answers": [ 
                    { "question_id": 44, "correct": 0, "incorrect": 0 }
                ]
            }
            
### List all exams [GET]

+ Response 200 (application/json)

    + Body
    
            {
                "exams": [
                    {
                        "id": 1,
                        "drill_id": 123,
                        "answers": [ 
                            { "question_id": 44, "correct": 0, "incorrect": 0 }
                        ]
                    }
                ]
            }


            
## Exam [/user/{user_id}/exam/{exam_id}]

+ Parameters

    + user_id (number) - ID of relevant user
    + exam_id (number) - ID of relevant exam

### Get exam details [GET]

+ Response 200 (application/json)

    + Body
    
            {
                "id": 1,
                "drill_id": 123,
                "answers": [ 
                    { "question_id": 44, "correct": 0, "incorrect": 0 }
                ]
            }
            
### Update exam with answers [POST]

+ Request (application/json)

        {
            "answers": [
                {
                    "question_id": 44,
                    "correct": true
                }, 
                {
                    "question_id": 12,
                    "correct": false
                }
            ]
        }
        
+ Response 200 (application/json)

## Answering question [/user/{user_id}/exam/{exam_id}/question/{question_id}]

+ Parameters

    + user_id (number) - ID of relevant user
    + exam_id (number) - ID of relevant exam
    + question_id (number) - ID of relevant question

### Get question in exam [GET]

+ Response 200 (application/json)

    + Body
    
            {
                "id": 44,
                "text": "Ako sa mas??"
                "answers": [
                    { "text": "Super!", "correct": false },
                    { "text": "Fakt naprd...", "correct": true },
                    { "text": "Idem na pivo.", "correct": true }
                ]
            }